### ISSUE TITLE
[META] Support Latest Python Version (3.10+) and other Distribution Channels

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark#220]
**Is your feature request related to a problem? Please describe.**
Latest python versions (3.10 and 3.11) are not supported. Only Python version 3.8 and 3.9 is supported.

**Describe the solution you'd like**
OSB should have support for python version 3.10 and 3.11

Steps:
- [x] Validate OSB works in environments with Python 3.8 and 3.9
- [x] Validate OSB works in environments with new Python Versions 3.10 and 3.11
- [x] Validate support in for the following OS: MacOS, Ubuntu, and Amazon Linux 2 (AL2)

**Describe alternatives you've considered**
N/A
**Additional context**
None

**Comment by IanHoang** [comment]
### **Summary**

Validated Python 3.8, 3.9, 3.10, and 3.11 works with opensearch-benchmark (OSB) in clean environments by spinning up Amazon EC2 instances with the bare minimum requirements needed to get OSB setup. EC2 instances were based in AL2 and Ubuntu. To test MacOS, I used my local Macbook. Pyenv was used to install python versions 3.8, 3.9, 3.10, and 3.11 across all setups. 

### Issues Encountered and Resolved
I had issues validating OSB working on Python 3.8 and Python 3.9. However, when adding support for Python 3.10 and Python 3.11, I encountered a few issues that are noted below.

**Updated Dependencies - Yappi and Tabulate**
After git cloning the repository, I would run install the project in editable mode (i.e. `python3 -m pip install -e .`) and encountered this yappi installation issue: 
```
Installing collected packages: yappi, thespian, tabulate, pyasn1, py-cpuinfo, ijson, zipp, urllib3, six, rsa, pyrsistent, pyasn1-modules, psutil, multidict, markupsafe, idna, google-crc32c, frozenlist, charset-normalizer, certifi, cachetools, attrs, async-timeout, yarl, opensearch-py, Jinja2, importlib-metadata, google-resumable-media, google-auth, aiosignal, jsonschema, aiohttp, opensearch-benchmark
  Running setup.py install for yappi ... error
  error: subprocess-exited-with-error

  × Running setup.py install for yappi did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      running install
...
× Encountered error while trying to install package.
╰─> yappi
```
**Solution**: Updated yappi to the latest version (from v1.2.3 to v1.4.0). 

After successfullly installing the repository in editable mode, environments with python 3.10 and 3.11 experienced the following issue when invoking opensearch-benchmark. The issue seemed to highlight a change in tabulate.
```
  File "/home/ubuntu/opensearch-benchmark/osbenchmark/benchmark.py", line 36, in <module>
    from osbenchmark import PROGRAM_NAME, BANNER, FORUM_LINK, SKULL, check_python_version, doc_link, telemetry
  File "/home/ubuntu/opensearch-benchmark/osbenchmark/telemetry.py", line 32, in <module>
    import tabulate
  File "/home/ubuntu/.pyenv/versions/3.10.6/lib/python3.10/site-packages/tabulate.py", line 16, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' 
```

**Solution**: Error went away after updating tabulate version (from v0.8.7 to v0.9.0). Newer versions of tabulate load `Iterable` from `abc` and not from `collections`, as it did in prior versions. 

I also began to receive deprecation warnings when pip installing the repository in editable mode, which I resolved by adding `wheel==0.38.4` to setup.py. 


### **Reproducible Testing Setups**
1. Set up the new environments with bare minimum dependencies needed to get OSB up and running.
2. Verify that pyenv is using the desired python version by running the following:
```
# To switch to Python version
pyenv local <PYTHON_VERSION>

# To verify that pyenv is using Python Version just set. For first option, "*" should be next to the python version of choice. For second option, it should output the python version you set earlier. 
pyenv versions 
Python3 -V
```
3. Ran end-to-end tests on EC2 instsances and local computer targeting an OpenSearch cluster. For interest in time, in each setup, two geonames tests were run with and without `--test-mode` flag. See examples below:
- With test mode flag:
```
bash -x /home/ubuntu/.pyenv/shims/opensearch-benchmark execute_test --workload=geonames --pipeline=benchmark-only --target-host="<OPENSEARCH CLUSTER ENDPOINT>" --client-options="basic_auth_user:'<USERNAME>',basic_auth_password:'<PASSWORD>'" --test-mode"
```
- Without test mode flag:
```
bash -x /home/ubuntu/.pyenv/shims/opensearch-benchmark execute_test --workload=geonames --pipeline=benchmark-only --target-host="<OPENSEARCH CLUSTER ENDPOINT>" --client-options="basic_auth_user:'<USERNAME>',basic_auth_password:'<PASSWORD>'"
```
